// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import { eagerLoadControllersFrom } from "@hotwired/stimulus-loading"
eagerLoadControllersFrom("controllers", application)

import CepController from "./cep_controller"
application.register("cep", CepController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HistoryFiltersController from "./history_filters_controller"
application.register("history-filters", HistoryFiltersController)

import LocationController from "./location_controller"
application.register("location", LocationController)

import MapController from "./map_controller"
application.register("map", MapController)

import PreventMultiSubmitController from "./prevent_multi_submit_controller"
application.register("prevent-multi-submit", PreventMultiSubmitController)

import SchedulesController from "./schedules_controller"
application.register("schedules", SchedulesController)
